spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccarrot_gallery?serverTimezone=Asia/Seoul
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

server:
  port: 8070